"""Изменение типа данных столбца для хранения пароля

Revision ID: 624dba8f504c
Revises: b3fe4eac0812
Create Date: 2023-12-10 02:38:31.878002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '624dba8f504c'
down_revision = 'b3fe4eac0812'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('User', 'password', type_=sa.Text,

    schema='FlaskSite'
    )
    
    # ### end Alembic commands ###
