"""Добавление столбца описание в таблицу Product, для карточек товара

Revision ID: 7c3828446905
Revises: 624dba8f504c
Create Date: 2023-12-10 02:46:10.422588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c3828446905'
down_revision = '624dba8f504c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.add_column('Product', sa.Column('Description', sa.Text(), nullable=True),
                  
    schema='FlaskSite'
    )