"""Added product relationship to CartProduct table

Revision ID: 9124421f01e9
Revises: 082a7a8726c5
Create Date: 2023-12-14 05:28:45.882697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9124421f01e9'
down_revision = '082a7a8726c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='FlaskSite'
    )
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=120), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username'),
    schema='FlaskSite'
    )
    op.create_table('Cart',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['FlaskSite.User.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='FlaskSite'
    )
    op.create_table('Order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('delivery_address', sa.String(length=200), nullable=False),
    sa.Column('delivery_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['FlaskSite.User.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='FlaskSite'
    )
    op.create_table('Product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['FlaskSite.Category.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='FlaskSite'
    )
    op.create_table('Shipping_address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['FlaskSite.User.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='FlaskSite'
    )
    op.create_table('Cart_product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cart_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cart_id'], ['FlaskSite.Cart.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['FlaskSite.Product.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='FlaskSite'
    )
    op.create_table('Order_product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['FlaskSite.Order.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['FlaskSite.Product.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='FlaskSite'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Order_product', schema='FlaskSite')
    op.drop_table('Cart_product', schema='FlaskSite')
    op.drop_table('Shipping_address', schema='FlaskSite')
    op.drop_table('Product', schema='FlaskSite')
    op.drop_table('Order', schema='FlaskSite')
    op.drop_table('Cart', schema='FlaskSite')
    op.drop_table('User', schema='FlaskSite')
    op.drop_table('Category', schema='FlaskSite')
    # ### end Alembic commands ###
