"""empty message

Revision ID: d23f59800fb6
Revises: 8c20b721a429
Create Date: 2023-12-10 03:59:41.964109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd23f59800fb6'
down_revision = '8c20b721a429'
branch_labels = None
depends_on = None


def upgrade():
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass